import 'package:islami_app/models/sura_data_model.dart';

abstract class Constants {

  List<String> arabicQuranSuras = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];
  List<String> englishQuranSuras = [
    "Al-Fatiha",
    "Al-Baqarah",
    "Aal-E-Imran",
    "An-Nisa'",
    "Al-Ma'idah",
    "Al-An'am",
    "Al-A'raf",
    "Al-Anfal",
    "At-Tawbah",
    "Yunus",
    "Hud",
    "Yusuf",
    "Ar-Ra'd",
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Al-Isra",
    "Al-Kahf",
    "Maryam",
    "Ta-Ha",
    "Al-Anbiya",
    "Al-Hajj",
    "Al-Mu'minun",
    "An-Nur",
    "Al-Furqan",
    "Ash-Shu'ara",
    "An-Naml",
    "Al-Qasas",
    "Al-Ankabut",
    "Ar-Rum",
    "Luqman",
    "As-Sajda",
    "Al-Ahzab",
    "Saba",
    "Fatir",
    "Ya-Sin",
    "As-Saffat",
    "Sad",
    "Az-Zumar",
    "Ghafir",
    "Fussilat",
    "Ash-Shura",
    "Az-Zukhruf",
    "Ad-Dukhan",
    "Al-Jathiya",
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Adh-Dhariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'a",
    "Al-Hadid",
    "Al-Mujadila",
    "Al-Hashr",
    "Al-Mumtahina",
    "As-Saff",
    "Al-Jumu'a",
    "Al-Munafiqun",
    "At-Taghabun",
    "At-Talaq",
    "At-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma'arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddathir",
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat",
    "An-Naba'",
    "An-Nazi'at",
    "Abasa",
    "At-Takwir",
    "Al-Infitar",
    "Al-Mutaffifin",
    "Al-Inshiqaq",
    "Al-Buruj",
    "At-Tariq",
    "Al-A'la",
    "Al-Ghashiyah",
    "Al-Fajr",
    "Al-Balad",
    "Ash-Shams",
    "Al-Lail",
    "Ad-Duha",
    "Ash-Sharh",
    "At-Tin",
    "Al-Alaq",
    "Al-Qadr",
    "Al-Bayyina",
    "Az-Zalzalah",
    "Al-Adiyat",
    "Al-Qari'a",
    "At-Takathur",
    "Al-Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraysh",
    "Al-Ma'un",
    "Al-Kawthar",
    "Al-Kafirun",
    "An-Nasr",
    "Al-Masad",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas"
  ];
  List<String> ayaNumber = [
    '7',
    '286',
    '200',
    '176',
    '120',
    '165',
    '206',
    '75',
    '129',
    '109',
    '123',
    '111',
    '43',
    '52',
    '99',
    '128',
    '111',
    '110',
    '98',
    '135',
    '112',
    '78',
    '118',
    '64',
    '77',
    '227',
    '93',
    '88',
    '69',
    '60',
    '34',
    '30',
    '73',
    '54',
    '45',
    '83',
    '182',
    '88',
    '75',
    '85',
    '54',
    '53',
    '89',
    '59',
    '37',
    '35',
    '38',
    '29',
    '18',
    '45',
    '60',
    '49',
    '62',
    '55',
    '78',
    '96',
    '29',
    '22',
    '24',
    '13',
    '14',
    '11',
    '11',
    '18',
    '12',
    '12',
    '30',
    '52',
    '52',
    '44',
    '28',
    '28',
    '20',
    '56',
    '40',
    '31',
    '50',
    '40',
    '46',
    '42',
    '29',
    '19',
    '36',
    '25',
    '22',
    '17',
    '19',
    '26',
    '30',
    '20',
    '15',
    '21',
    '11',
    '8',
    '5',
    '19',
    '5',
    '8',
    '8',
    '11',
    '11',
    '8',
    '3',
    '9',
    '5',
    '4',
    '6',
    '3',
    '6',
    '3',
    '5',
    '4',
    '5',
    '6'
  ];

  static List<SuraDataModel> suraDataList = [
    SuraDataModel(suraID: 1, suraNameEN: "Al-Fatiha", suraNameAR: "الفاتحه", suraVersusNumber: "7"),
    SuraDataModel(suraID: 2, suraNameEN: "Al-Baqarah", suraNameAR: "البقرة", suraVersusNumber: "286"),
    SuraDataModel(suraID: 3, suraNameEN: "Aal-E-Imran", suraNameAR: "آل عمران", suraVersusNumber: "200"),
    SuraDataModel(suraID: 4, suraNameEN: "An-Nisa'", suraNameAR: "النساء", suraVersusNumber: "176"),
    SuraDataModel(suraID: 5, suraNameEN: "Al-Ma'idah", suraNameAR: "المائدة", suraVersusNumber: "120"),
    SuraDataModel(suraID: 6, suraNameEN: "Al-An'am", suraNameAR: "الأنعام", suraVersusNumber: "165"),
    SuraDataModel(suraID: 7, suraNameEN: "Al-A'raf", suraNameAR: "الأعراف", suraVersusNumber: "206"),
    SuraDataModel(suraID: 8, suraNameEN: "Al-Anfal", suraNameAR: "الأنفال", suraVersusNumber: "75"),
    SuraDataModel(suraID: 9, suraNameEN: "At-Tawbah", suraNameAR: "التوبة", suraVersusNumber: "129"),
    SuraDataModel(suraID: 10, suraNameEN: "Yunus", suraNameAR: "يونس", suraVersusNumber: "109"),
    SuraDataModel(suraID: 11, suraNameEN: "Hud", suraNameAR: "هود", suraVersusNumber: "123"),
    SuraDataModel(suraID: 12, suraNameEN: "Yusuf", suraNameAR: "يوسف", suraVersusNumber: "111"),
    SuraDataModel(suraID: 13, suraNameEN: "Ar-Ra'd", suraNameAR: "الرعد", suraVersusNumber: "43"),
    SuraDataModel(suraID: 14, suraNameEN: "Ibrahim", suraNameAR: "إبراهيم", suraVersusNumber: "52"),
    SuraDataModel(suraID: 15, suraNameEN: "Al-Hijr", suraNameAR: "الحجر", suraVersusNumber: "99"),
    SuraDataModel(suraID: 16, suraNameEN: "An-Nahl", suraNameAR: "النحل", suraVersusNumber: "128"),
    SuraDataModel(suraID: 17, suraNameEN: "Al-Isra", suraNameAR: "الإسراء", suraVersusNumber: "111"),
    SuraDataModel(suraID: 18, suraNameEN: "Al-Kahf", suraNameAR: "الكهف", suraVersusNumber: "110"),
    SuraDataModel(suraID: 19, suraNameEN: "Maryam", suraNameAR: "مريم", suraVersusNumber: "98"),
    SuraDataModel(suraID: 20, suraNameEN: "Ta-Ha", suraNameAR: "طه", suraVersusNumber: "135"),
    SuraDataModel(suraID: 21, suraNameEN: "Al-Anbiya", suraNameAR: "الأنبياء", suraVersusNumber: "112"),
    SuraDataModel(suraID: 22, suraNameEN: "Al-Hajj", suraNameAR: "الحج", suraVersusNumber: "78"),
    SuraDataModel(suraID: 23, suraNameEN: "Al-Mu'minun", suraNameAR: "المؤمنون", suraVersusNumber: "118"),
    SuraDataModel(suraID: 24, suraNameEN: "An-Nur", suraNameAR: "النّور", suraVersusNumber: "64"),
    SuraDataModel(suraID: 25, suraNameEN: "Al-Furqan", suraNameAR: "الفرقان", suraVersusNumber: "77"),
    SuraDataModel(suraID: 26, suraNameEN: "Ash-Shu'ara", suraNameAR: "الشعراء", suraVersusNumber: "227"),
    SuraDataModel(suraID: 27, suraNameEN: "An-Naml", suraNameAR: "النّمل", suraVersusNumber: "93"),
    SuraDataModel(suraID: 28, suraNameEN: "Al-Qasas", suraNameAR: "القصص", suraVersusNumber: "88"),
    SuraDataModel(suraID: 29, suraNameEN: "Al-Ankabut", suraNameAR: "العنكبوت", suraVersusNumber: "69"),
    SuraDataModel(suraID: 30, suraNameEN: "Ar-Rum", suraNameAR: "الرّوم", suraVersusNumber: "60"),
    SuraDataModel(suraID: 31, suraNameEN: "Luqman", suraNameAR: "لقمان", suraVersusNumber: "34"),
    SuraDataModel(suraID: 32, suraNameEN: "As-Sajda", suraNameAR: "السجدة", suraVersusNumber: "30"),
    SuraDataModel(suraID: 33, suraNameEN: "Al-Ahzab", suraNameAR: "الأحزاب", suraVersusNumber: "73"),
    SuraDataModel(suraID: 34, suraNameEN: "Saba", suraNameAR: "سبأ", suraVersusNumber: "54"),
    SuraDataModel(suraID: 35, suraNameEN: "Fatir", suraNameAR: "فاطر", suraVersusNumber: "45"),
    SuraDataModel(suraID: 36, suraNameEN: "Ya-Sin", suraNameAR: "يس", suraVersusNumber: "83"),
    SuraDataModel(suraID: 37, suraNameEN: "As-Saffat", suraNameAR: "الصافات", suraVersusNumber: "182"),
    SuraDataModel(suraID: 38, suraNameEN: "Sad", suraNameAR: "ص", suraVersusNumber: "88"),
    SuraDataModel(suraID: 39, suraNameEN: "Az-Zumar", suraNameAR: "الزمر", suraVersusNumber: "75"),
    SuraDataModel(suraID: 40, suraNameEN: "Ghafir", suraNameAR: "غافر", suraVersusNumber: "85"),
    SuraDataModel(suraID: 41, suraNameEN: "Fussilat", suraNameAR: "فصّلت", suraVersusNumber: "54"),
    SuraDataModel(suraID: 42, suraNameEN: "Ash-Shura", suraNameAR: "الشورى", suraVersusNumber: "53"),
    SuraDataModel(suraID: 43, suraNameEN: "Az-Zukhruf", suraNameAR: "الزخرف", suraVersusNumber: "89"),
    SuraDataModel(suraID: 44, suraNameEN: "Ad-Dukhan", suraNameAR: "الدّخان", suraVersusNumber: "59"),
    SuraDataModel(suraID: 45, suraNameEN: "Al-Jathiya", suraNameAR: "الجاثية", suraVersusNumber: "37"),
    SuraDataModel(suraID: 46, suraNameEN: "Al-Ahqaf", suraNameAR: "الأحقاف", suraVersusNumber: "35"),
    SuraDataModel(suraID: 47, suraNameEN: "Muhammad", suraNameAR: "محمد", suraVersusNumber: "38"),
    SuraDataModel(suraID: 48, suraNameEN: "Al-Fath", suraNameAR: "الفتح", suraVersusNumber: "29"),
    SuraDataModel(suraID: 49, suraNameEN: "Al-Hujurat", suraNameAR: "الحجرات", suraVersusNumber: "18"),
    SuraDataModel(suraID: 50, suraNameEN: "Qaf", suraNameAR: "ق", suraVersusNumber: "45"),
    SuraDataModel(suraID: 51, suraNameEN: "Adh-Dhariyat", suraNameAR: "الذاريات", suraVersusNumber: "60"),
    SuraDataModel(suraID: 52, suraNameEN: "At-Tur", suraNameAR: "الطور", suraVersusNumber: "49"),
    SuraDataModel(suraID: 53, suraNameEN: "An-Najm", suraNameAR: "النجم", suraVersusNumber: "62"),
    SuraDataModel(suraID: 54, suraNameEN: "Al-Qamar", suraNameAR: "القمر", suraVersusNumber: "55"),
    SuraDataModel(suraID: 55, suraNameEN: "Ar-Rahman", suraNameAR: "الرحمن", suraVersusNumber: "78"),
    SuraDataModel(suraID: 56, suraNameEN: "Al-Waqi'a", suraNameAR: "الواقعة", suraVersusNumber: "96"),
    SuraDataModel(suraID: 57, suraNameEN: "Al-Hadid", suraNameAR: "الحديد", suraVersusNumber: "29"),
    SuraDataModel(suraID: 58, suraNameEN: "Al-Mujadila", suraNameAR: "المجادلة", suraVersusNumber: "22"),
    SuraDataModel(suraID: 59, suraNameEN: "Al-Hashr", suraNameAR: "الحشر", suraVersusNumber: "24"),
    SuraDataModel(suraID: 60, suraNameEN: "Al-Mumtahina", suraNameAR: "الممتحنة", suraVersusNumber: "13"),
    SuraDataModel(suraID: 61, suraNameEN: "As-Saff", suraNameAR: "الصف", suraVersusNumber: "14"),
    SuraDataModel(suraID: 62, suraNameEN: "Al-Jumu'a", suraNameAR: "الجمعة", suraVersusNumber: "11"),
    SuraDataModel(suraID: 63, suraNameEN: "Al-Munafiqun", suraNameAR: "المنافقون", suraVersusNumber: "11"),
    SuraDataModel(suraID: 64, suraNameEN: "At-Taghabun", suraNameAR: "التغابن", suraVersusNumber: "18"),
    SuraDataModel(suraID: 65, suraNameEN: "At-Talaq", suraNameAR: "الطلاق", suraVersusNumber: "12"),
    SuraDataModel(suraID: 66, suraNameEN: "At-Tahrim", suraNameAR: "التحريم", suraVersusNumber: "12"),
    SuraDataModel(suraID: 67, suraNameEN: "Al-Mulk", suraNameAR: "الملك", suraVersusNumber: "30"),
    SuraDataModel(suraID: 68, suraNameEN: "Al-Qalam", suraNameAR: "القلم", suraVersusNumber: "52"),
    SuraDataModel(suraID: 69, suraNameEN: "Al-Haqqah", suraNameAR: "الحاقة", suraVersusNumber: "52"),
    SuraDataModel(suraID: 70, suraNameEN: "Al-Ma'arij", suraNameAR: "المعارج", suraVersusNumber: "44"),
    SuraDataModel(suraID: 71, suraNameEN: "Nuh", suraNameAR: "نوح", suraVersusNumber: "28"),
    SuraDataModel(suraID: 72, suraNameEN: "Al-Jinn", suraNameAR: "الجن", suraVersusNumber: "28"),
    SuraDataModel(suraID: 73, suraNameEN: "Al-Muzzammil", suraNameAR: "المزّمّل", suraVersusNumber: "20"),
    SuraDataModel(suraID: 74, suraNameEN: "Al-Muddathir", suraNameAR: "المدّثر", suraVersusNumber: "56"),
    SuraDataModel(suraID: 75, suraNameEN: "Al-Qiyamah", suraNameAR: "القيامة", suraVersusNumber: "40"),
    SuraDataModel(suraID: 76, suraNameEN: "Al-Insan", suraNameAR: "الإنسان", suraVersusNumber: "31"),
    SuraDataModel(suraID: 77, suraNameEN: "Al-Mursalat", suraNameAR: "المرسلات", suraVersusNumber: "50"),
    SuraDataModel(suraID: 78, suraNameEN: "An-Naba'", suraNameAR: "النبأ", suraVersusNumber: "40"),
    SuraDataModel(suraID: 79, suraNameEN: "An-Nazi'at", suraNameAR: "النازعات", suraVersusNumber: "46"),
    SuraDataModel(suraID: 80, suraNameEN: "Abasa", suraNameAR: "عبس", suraVersusNumber: "42"),
    SuraDataModel(suraID: 81, suraNameEN: "At-Takwir", suraNameAR: "التكوير", suraVersusNumber: "29"),
    SuraDataModel(suraID: 82, suraNameEN: "Al-Infitar", suraNameAR: "الإنفطار", suraVersusNumber: "19"),
    SuraDataModel(suraID: 83, suraNameEN: "Al-Mutaffifin", suraNameAR: "المطفّفين", suraVersusNumber: "36"),
    SuraDataModel(suraID: 84, suraNameEN: "Al-Inshiqaq", suraNameAR: "الإنشقاق", suraVersusNumber: "25"),
    SuraDataModel(suraID: 85, suraNameEN: "Al-Buruj", suraNameAR: "البروج", suraVersusNumber: "22"),
    SuraDataModel(suraID: 86, suraNameEN: "At-Tariq", suraNameAR: "الطارق", suraVersusNumber: "17"),
    SuraDataModel(suraID: 87, suraNameEN: "Al-A'la", suraNameAR: "الأعلى", suraVersusNumber: "19"),
    SuraDataModel(suraID: 88, suraNameEN: "Al-Ghashiyah", suraNameAR: "الغاشية", suraVersusNumber: "26"),
    SuraDataModel(suraID: 89, suraNameEN: "Al-Fajr", suraNameAR: "الفجر", suraVersusNumber: "30"),
    SuraDataModel(suraID: 90, suraNameEN: "Al-Balad", suraNameAR: "البلد", suraVersusNumber: "20"),
    SuraDataModel(suraID: 91, suraNameEN: "Ash-Shams", suraNameAR: "الشمس", suraVersusNumber: "15"),
    SuraDataModel(suraID: 92, suraNameEN: "Al-Lail", suraNameAR: "الليل", suraVersusNumber: "21"),
    SuraDataModel(suraID: 93, suraNameEN: "Ad-Duha", suraNameAR: "الضحى", suraVersusNumber: "11"),
    SuraDataModel(suraID: 94, suraNameEN: "Ash-Sharh", suraNameAR: "الشرح", suraVersusNumber: "8"),
    SuraDataModel(suraID: 95, suraNameEN: "At-Tin", suraNameAR: "التين", suraVersusNumber: "8"),
    SuraDataModel(suraID: 96, suraNameEN: "Al-Alaq", suraNameAR: "العلق", suraVersusNumber: "19"),
    SuraDataModel(suraID: 97, suraNameEN: "Al-Qadr", suraNameAR: "القدر", suraVersusNumber: "5"),
    SuraDataModel(suraID: 98, suraNameEN: "Al-Bayyina", suraNameAR: "البينة", suraVersusNumber: "8"),
    SuraDataModel(suraID: 99, suraNameEN: "Az-Zalzalah", suraNameAR: "الزلزلة", suraVersusNumber: "8"),
    SuraDataModel(suraID: 100, suraNameEN: "Al-Adiyat", suraNameAR: "العاديات", suraVersusNumber: "11"),
    SuraDataModel(suraID: 101, suraNameEN: "Al-Qari'a", suraNameAR: "القارعة", suraVersusNumber: "11"),
    SuraDataModel(suraID: 102, suraNameEN: "At-Takathur", suraNameAR: "التكاثر", suraVersusNumber: "8"),
    SuraDataModel(suraID: 103, suraNameEN: "Al-Asr", suraNameAR: "العصر", suraVersusNumber: "3"),
    SuraDataModel(suraID: 104, suraNameEN: "Al-Humazah", suraNameAR: "الهمزة", suraVersusNumber: "9"),
    SuraDataModel(suraID: 105, suraNameEN: "Al-Fil", suraNameAR: "الفيل", suraVersusNumber: "5"),
    SuraDataModel(suraID: 106, suraNameEN: "Quraysh", suraNameAR: "قريش", suraVersusNumber: "4"),
    SuraDataModel(suraID: 107, suraNameEN: "Al-Ma'un", suraNameAR: "الماعون", suraVersusNumber: "7"),
    SuraDataModel(suraID: 108, suraNameEN: "Al-Kawthar", suraNameAR: "الكوثر", suraVersusNumber: "3"),
    SuraDataModel(suraID: 109, suraNameEN: "Al-Kafirun", suraNameAR: "الكافرون", suraVersusNumber: "6"),
    SuraDataModel(suraID: 110, suraNameEN: "An-Nasr", suraNameAR: "النصر", suraVersusNumber: "3"),
    SuraDataModel(suraID: 111, suraNameEN: "Al-Masad", suraNameAR: "المسد", suraVersusNumber: "5"),
    SuraDataModel(suraID: 112, suraNameEN: "Al-Ikhlas", suraNameAR: "الإخلاص", suraVersusNumber: "4"),
    SuraDataModel(suraID: 113, suraNameEN: "Al-Falaq", suraNameAR: "الفلق", suraVersusNumber: "5"),
    SuraDataModel(suraID: 114, suraNameEN: "An-Nas", suraNameAR: "الناس", suraVersusNumber: "6")
  ];

}